### ISSUE TITLE
Add social network on my profile on ‘My habits’ page 

### ISSUE THREAD

**Issue by GreenCity23** [GreenCity23/GreenCityProject#114]
**As a** Logged User **I want to** add social networks and edit profiles on the ‘My habits’ page.
![Знімок екрана 2020-07-14 о 22 20 03](https://user-images.githubusercontent.com/65448781/88525080-d2995e80-d002-11ea-9c39-d2fba5c72977.png)

**Acceptance criteria:**

1. 'Linked social networks' module is not mandatory.

2. When the User clicks the 'Edit' icon, he/she is directed to the filled-out Edit profile form, where he/she has the possibility to add, edit, and delete social networks.

3. Logged User can add two or more accounts from one social network. 

4. Logged User can't add more than 5 social networks.

5. When the User adds, edits, or deletes social networks, he/she should have the possibility to 'Save' the selected area or 'Cancel' the selection.

6. When the user clicks the ‘Save’ button, the social networks will be changed in the system.

7. When the user clicks the ‘Cancel’ button, the social networks will not be changed in the system.

8. A link for the social network should be enabled. 

9. When the User clicks on an icon of the social network, he/she should be redirected to the page of the chosen social network.

~~User story:  [GC-1489](https://jira.softserve.academy/browse/GC-1489)~~
Change request #121 , #122  ,#129

### Tasks:

1. [ ] Create UI (markup and styles from mockup); (Julia) #118 
2. [ ] Create BL (necessary CRUD methods for social networks, relations with parent component); (Roman)
4. [ ] Show social networks in profile;
6. [ ] Pull request;
7. [ ] Merge;
