### ISSUE TITLE
'Edit Profile’ responsive design

### ISSUE THREAD

**Issue by GreenCity23** [GreenCity23/GreenCityProject#118]
**As a** User, **I want to** have a responsive design for edit ‘My habits’  functionality, **so that I** can edit profiles from different devices.
Breakpoints 1140, 1024, 768, 576, 320 are done due to provided mockups.

~~User story  [GC-1411](https://jira.softserve.academy/browse/GC-1411)~~

**Acceptance criteria:**

1) The "Edit profile" page should consist of the following parts:
- Edit photo;
- Personal info;
- Linked social networks;
- Profile privacy;
- Buttons.
2) When the user clicks the 'Edit' icon, he/she is directed to the filled-out 'Edit profile' form with reference: 'https://ita-social-projects.github.io/GreenCityClient/#/profile/USER ID/edit'.
3) The page must have a responsive design. According to Mock-up.

**Tasks:**

- [ ] Create component 'edit profile';

- [x] Add route for this page;

- [x] Create subsidiaries components;

- [x] Create HTML markup and place the components in the correct order;

- [x] Add breakpoints;

- [x]  Pull request;

- [ ]  Merge;

**Mock-up:**

Details at Figma

1140
![Знімок екрана 2020-07-22 о 23 19 34](https://user-images.githubusercontent.com/65448781/88526022-16409800-d004-11ea-8de2-82c2c71089ef.png)
1024
![Знімок екрана 2020-07-22 о 23 19 46](https://user-images.githubusercontent.com/65448781/88526058-1f316980-d004-11ea-8c9d-ae1f1024f9f4.png)
768
![Знімок екрана 2020-07-22 о 23 20 09](https://user-images.githubusercontent.com/65448781/88526111-2ce6ef00-d004-11ea-9eae-168ffa00a60f.png)
576
![Знімок екрана 2020-07-22 о 23 20 21](https://user-images.githubusercontent.com/65448781/88526134-3708ed80-d004-11ea-97e2-309540c720d0.png)
320
![Знімок екрана 2020-07-22 о 23 20 36](https://user-images.githubusercontent.com/65448781/88526162-40925580-d004-11ea-9521-1e4b9960b907.png)
